/**
 * `npm run brand:assets`: embeds the files the Worker serves from
 * assets/brand/ into src/marketing/brand-assets.generated.ts. This Worker
 * has no static-asset pipeline, so images ship inside the bundle. Rerun
 * after changing anything in assets/brand/.
 */
import { readFileSync, writeFileSync } from "node:fs";

const png = (file: string) => Buffer.from(readFileSync(`assets/brand/${file}`)).toString("base64");
const svg = (file: string) => readFileSync(`assets/brand/${file}`, "utf8").trim();

const out = `// Generated by scripts/generate-brand-assets.ts from assets/brand/. Don't edit by hand.
export const ICON_SVG = ${JSON.stringify(svg("mark.svg"))};
export const ICON_SMALL_SVG = ${JSON.stringify(svg("mark-small.svg"))};
export const ICON_512_PNG_BASE64 = ${JSON.stringify(png("mark-512.png"))};
export const ICON_180_PNG_BASE64 = ${JSON.stringify(png("mark-180.png"))};
export const OG_PNG_BASE64 = ${JSON.stringify(png("og.png"))};
`;
writeFileSync("src/marketing/brand-assets.generated.ts", out);
console.log(`wrote src/marketing/brand-assets.generated.ts (${Math.round(out.length / 1024)} KB)`);
